const state = { apiBase: localStorage.getItem('agent.apiBase') || 'http://localhost:8080', history: [], profile: null };
const $ = (id) => document.getElementById(id);

function api(path, options = {}) {
  const base = (state.apiBase || '').replace(/\/$/, '');
  return fetch(`${base}${path}`, { ...options, headers: { ...(options.body instanceof FormData ? {} : {'Content-Type': 'application/json'}), ...(options.headers || {}) } })
    .then(async response => { const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message || `HTTP ${response.status}`); return body; });
}
function showView(name) { document.querySelectorAll('.view').forEach(v => v.classList.toggle('active', v.id === `view-${name}`)); document.querySelectorAll('.nav-item').forEach(v => v.classList.toggle('active', v.dataset.view === name)); if (name === 'history' || name === 'dashboard') loadHistory(); if (name === 'profile') loadProfile(); }
function text(value) { return value == null || value === '' ? '—' : String(value); }
function list(items) { return Array.isArray(items) && items.length ? `<ul class="list">${items.map(x => `<li>${escapeHtml(x)}</li>`).join('')}</ul>` : '<div class="empty">暂无</div>'; }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function loadHistory() { api('/api/jobs/recent?limit=20').then(rows => { state.history = rows || []; renderHistory(); }).catch(error => { $('dashboardRecent').innerHTML = `<span class="error">${escapeHtml(error.message)}</span>`; $('historyList').innerHTML = `<span class="error">${escapeHtml(error.message)}</span>`; }); }
function renderHistory() { const rows = state.history; $('metricAnalyses').textContent = rows.length; $('metricRecommended').textContent = rows.filter(x => /投|recommend|建议/i.test(`${x.aiDecision || ''}${x.ruleConclusion || ''}`)).length; const scores = rows.map(x => x.aiScore).filter(x => typeof x === 'number'); $('metricScore').textContent = scores.length ? Math.round(scores.reduce((a,b) => a+b, 0) / scores.length) : '—'; const markup = rows.length ? rows.slice(0,6).map(x => `<div class="history-row"><div><strong>${escapeHtml(text(x.jobTitle))}</strong><small>${escapeHtml(text(x.companyName))}</small></div><div>${escapeHtml(text(x.city))}</div><div><span class="pill">${escapeHtml(text(x.aiDecision || x.ruleConclusion))}</span></div><div>${text(x.aiScore || x.ruleScore)} 分</div></div>`).join('') : '<div class="empty">暂无分析记录</div>'; $('dashboardRecent').innerHTML = markup; $('historyList').innerHTML = rows.length ? rows.map(x => `<div class="history-row"><div><strong>${escapeHtml(text(x.jobTitle))}</strong><small>${escapeHtml(text(x.companyName))}</small></div><div>${escapeHtml(text(x.city))}<br><small>${escapeHtml(text(x.salary))}</small></div><div><span class="pill">${escapeHtml(text(x.aiDecision || x.ruleConclusion))}</span></div><div>${text(x.aiScore || x.ruleScore)} 分<br><small>ID ${text(x.jobRecordId)}</small></div></div>`).join('') : '<div class="empty">暂无分析记录</div>'; }
function loadProfile() { api('/api/profile/current').then(profile => { state.profile = profile; $('profileJson').textContent = JSON.stringify(profile, null, 2); }).catch(() => { $('profileJson').textContent = '暂无用户画像，上传 PDF 后生成。'; }); }
function uploadResume() { const file = $('resumeFile').files[0]; if (!file) { $('uploadStatus').textContent = '请选择 PDF'; return; } const data = new FormData(); data.append('file', file); $('uploadStatus').textContent = '解析与建索引中…'; api('/api/profile/resume/upload', { method: 'POST', body: data }).then(result => { $('uploadStatus').textContent = result.success ? '上传成功' : '处理完成'; $('resumeResult').innerHTML = [['文件',result.fileName],['页数',result.pageCount],['文本长度',result.textLength],['文档 ID',result.documentId],['Chunk 数',result.chunkCount]].map(x => `<div><span>${x[0]}</span><strong>${escapeHtml(text(x[1]))}</strong></div>`).join(''); loadProfile(); }).catch(error => { $('uploadStatus').innerHTML = `<span class="error">${escapeHtml(error.message)}</span>`; }); }
function renderAnalysis(result) { const rag = result.profileRag || {}; const chunks = rag.chunks || []; $('analysisResult').innerHTML = `<div class="result-card"><h3>结论 <span class="pill">${escapeHtml(text(result.decision))}</span></h3><div class="score">${text(result.score)}<small> / 100</small></div><p>${escapeHtml(text(result.direction))}</p><h3>匹配原因</h3>${list(result.reasons)}</div><div class="result-card"><h3>风险项</h3>${list(result.risks)}<h3>面试建议</h3>${list(result.interviewFocus)}</div><div class="result-card full"><h3>简历匹配与沟通建议</h3>${list(result.resumeMatches)}<p>${escapeHtml(text(result.suggestedMessage))}</p></div><div class="result-card full"><h3>RAG 证据 <span class="pill">${escapeHtml(text(rag.retrievalMode))} · ${chunks.length} chunks</span></h3>${chunks.length ? `<table class="trace-table"><thead><tr><th>标题</th><th>类型</th><th>来源</th><th>语义分</th><th>关键词分</th><th>权重</th><th>基础分</th><th>最终分</th></tr></thead><tbody>${chunks.map(c => `<tr><td>${escapeHtml(text(c.title))}</td><td>${escapeHtml(text(c.chunkType))}</td><td>${escapeHtml(text(c.sourceType))}</td><td>${text(c.semanticScore)}</td><td>${text(c.keywordScore)}</td><td>${text(c.chunkWeight)}</td><td>${text(c.baseScore)}</td><td>${text(c.finalScore)}</td></tr>`).join('')}</tbody></table>` : '<div class="empty">没有召回画像证据</div>'}</div>`; }
function analyzeJob() { const request = { jobTitle:$('jobTitle').value, companyName:$('companyName').value, salary:$('salary').value, city:$('city').value, schedule:$('schedule').value, duration:$('duration').value, jobText:$('jobText').value, ruleScore:null, ruleConclusion:null, capturedJobRecordId:$('capturedJobRecordId').value ? Number($('capturedJobRecordId').value) : null }; $('analysisStatus').textContent = '分析中…'; api('/api/job/analyze', { method:'POST', body:JSON.stringify(request) }).then(result => { $('analysisStatus').textContent = '完成'; renderAnalysis(result); }).catch(error => { $('analysisStatus').innerHTML = `<span class="error">${escapeHtml(error.message)}</span>`; }); }
function searchProfile() { const query = $('profileQuery').value.trim(); if (!query) return; api(`/api/profile/search?query=${encodeURIComponent(query)}&topK=5`).then(result => { $('profileSearchResult').innerHTML = result.chunks?.length ? result.chunks.map(c => `<div class="history-row"><div><strong>${escapeHtml(text(c.title))}</strong><small>${escapeHtml(text(c.chunkType))}</small></div><div>${escapeHtml(text(c.sourceType))}</div><div>语义 ${text(c.semanticScore)}</div><div>最终 ${text(c.finalScore ?? c.score)}</div></div>`).join('') : '<div class="empty">无召回结果</div>'; }).catch(error => { $('profileSearchResult').innerHTML = `<span class="error">${escapeHtml(error.message)}</span>`; }); }
function loadTrace() { const taskId = $('traceTaskId').value.trim(); if (!taskId) return; api(`/api/trace/${encodeURIComponent(taskId)}`).then(rows => { $('traceResult').innerHTML = rows?.length ? `<table class="trace-table"><thead><tr><th>阶段</th><th>耗时(ms)</th><th>开始时间</th><th>输入</th><th>输出</th></tr></thead><tbody>${rows.map(row => `<tr><td><span class="pill">${escapeHtml(text(row.stage))}</span></td><td>${text(row.latencyMs)}</td><td>${escapeHtml(text(row.createdTime))}</td><td><pre>${escapeHtml(text(row.inputData))}</pre></td><td><pre>${escapeHtml(text(row.outputData))}</pre></td></tr>`).join('')}</tbody></table>` : '<div class="empty">没有找到 Trace 记录</div>'; }).catch(error => { $('traceResult').innerHTML = `<span class="error">${escapeHtml(error.message)}</span>`; }); }
document.querySelectorAll('.nav-item').forEach(button => button.addEventListener('click', () => showView(button.dataset.view))); document.querySelectorAll('[data-go]').forEach(button => button.addEventListener('click', () => showView(button.dataset.go))); $('apiBase').value = state.apiBase; $('apiBase').addEventListener('change', event => { state.apiBase = event.target.value.trim(); localStorage.setItem('agent.apiBase', state.apiBase); }); $('uploadResume').addEventListener('click', uploadResume); $('refreshProfile').addEventListener('click', loadProfile); $('searchProfile').addEventListener('click', searchProfile); $('reindexProfile').addEventListener('click', () => api('/api/profile/reindex', { method:'POST' }).then(() => { $('uploadStatus').textContent = '索引已重建'; }).catch(error => { $('uploadStatus').textContent = error.message; })); $('analyzeJob').addEventListener('click', analyzeJob); $('refreshHistory').addEventListener('click', loadHistory); $('loadTrace').addEventListener('click', loadTrace); loadHistory();
